-- 1. 习惯配置同步表 (supabase_habits)
CREATE TABLE IF NOT EXISTS public.supabase_habits (
    id TEXT PRIMARY KEY,                       -- 本地 UUID 字符串形式
    name TEXT NOT NULL,                        -- 习惯名称
    icon TEXT NOT NULL,                        -- 图标名称
    frequency TEXT NOT NULL CHECK (frequency IN ('daily', 'weekly')),
    energy_demand TEXT NOT NULL CHECK (energy_demand IN ('high', 'medium', 'low')),
    "order" INTEGER DEFAULT 0,                 -- 拖拽排序顺序
    depends_on TEXT,                           -- 前置依赖的习惯 ID
    custom_form_type TEXT DEFAULT 'none',      -- 特化表单类型 ('none', 'fitness', 'social')
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL -- 最后更新时间
);

-- 2. 习惯打卡记录同步表 (supabase_habit_logs)
CREATE TABLE IF NOT EXISTS public.supabase_habit_logs (
    id TEXT PRIMARY KEY,                       -- 本地 UUID
    habit_id TEXT REFERENCES public.supabase_habits(id) ON DELETE CASCADE,
    date TEXT NOT NULL,                        -- 格式 'YYYY-MM-DD'
    custom_data JSONB DEFAULT NULL,            -- 特化打卡表单提交的 JSON 数据
    image_url TEXT DEFAULT NULL,               -- 打卡凭证图片 URL
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 创建索引以加速按日期和习惯ID的查询
CREATE INDEX IF NOT EXISTS idx_supabase_habit_logs_date ON public.supabase_habit_logs(date);
CREATE INDEX IF NOT EXISTS idx_supabase_habit_logs_habit_id ON public.supabase_habit_logs(habit_id);

-- 3. SM-2 卡片同步表 (supabase_cards)
CREATE TABLE IF NOT EXISTS public.supabase_cards (
    id TEXT PRIMARY KEY,                       -- 本地 UUID
    front TEXT NOT NULL,                       -- 正面内容 (Markdown)
    back TEXT NOT NULL,                        -- 背面内容 (Markdown)
    tags TEXT[] DEFAULT '{}',                  -- 标签数组
    linked_cards TEXT[] DEFAULT '{}',          -- 双向链接关联的卡片 ID 或标题
    reps INTEGER DEFAULT 0,                    -- 连续成功复习次数
    interval INTEGER DEFAULT 0,                -- 距离下一次复习的间隔天数
    ease NUMERIC DEFAULT 2.5,                  -- 简易度因子
    next_review TIMESTAMPTZ NOT NULL,          -- 下一次复习的时间
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_supabase_cards_next_review ON public.supabase_cards(next_review);

-- 4. 每日意图与状态同步表 (supabase_daily_records)
CREATE TABLE IF NOT EXISTS public.supabase_daily_records (
    date TEXT PRIMARY KEY,                     -- 格式 'YYYY-MM-DD'
    woop_wish TEXT,
    woop_outcome TEXT,
    woop_obstacle TEXT,
    woop_plan TEXT,
    energy_level INTEGER CHECK (energy_level >= 1 AND energy_level <= 10),
    review_questions TEXT[] DEFAULT '{}',      -- AI 生成的灵魂反思问题
    review_answers TEXT[] DEFAULT '{}',        -- 用户的回答
    review_completed_at TIMESTAMPTZ DEFAULT NULL,
    ai_tasks JSONB DEFAULT NULL,               -- 当天 AI 生成的排程任务 (JSONB Array)
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- 5. AI RAG 与 pgvector 向量搜索配置 (Vibe Coding 助手与第二大脑知识检索)
-- =========================================================================

-- 启用 pgvector 扩展 (如果尚未启用)
CREATE EXTENSION IF NOT EXISTS vector;

-- 创建技术笔记知识库表 (对应 Vibe Coding 错题本向量检索)
CREATE TABLE IF NOT EXISTS public.supabase_tech_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,                       -- 标题/错误现象
    content TEXT NOT NULL,                     -- 解决方案/详细说明
    embedding vector(1536),                    -- text-embedding-3-small (1536维) 向量
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 创建余弦相似度匹配函数 (RPC)
CREATE OR REPLACE FUNCTION match_tech_notes (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  title text,
  content text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    supabase_tech_notes.id,
    supabase_tech_notes.title,
    supabase_tech_notes.content,
    1 - (supabase_tech_notes.embedding <=> query_embedding) AS similarity
  FROM supabase_tech_notes
  WHERE 1 - (supabase_tech_notes.embedding <=> query_embedding) > match_threshold
  ORDER BY supabase_tech_notes.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;
